/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'id' : BookingId,
  'status' : BookingStatus,
  'clientId' : Principal,
  'paymentStatus' : PaymentStatus,
  'createdAt' : bigint,
  'clientNotes' : string,
  'updatedAt' : bigint,
  'totalPrice' : bigint,
  'location' : string,
  'packageId' : [] | [PackageId],
  'eventDate' : bigint,
  'equipmentIds' : Array<EquipmentId>,
  'eventType' : string,
}
export type BookingId = string;
export type BookingStatus = { 'Confirmed' : null } |
  { 'Cancelled' : null } |
  { 'Completed' : null } |
  { 'Pending' : null };
export interface ChecklistItem {
  'id' : string,
  'item' : string,
  'completed' : boolean,
  'assignedStaff' : string,
}
export interface CreateBookingRequest {
  'clientNotes' : string,
  'location' : string,
  'packageId' : [] | [PackageId],
  'eventDate' : bigint,
  'equipmentIds' : Array<EquipmentId>,
  'eventType' : string,
}
export interface CreateEquipmentRequest {
  'name' : string,
  'maintenanceNotes' : string,
  'category' : string,
  'unitPrice' : bigint,
  'totalQuantity' : bigint,
}
export interface CreatePackageRequest {
  'name' : string,
  'description' : string,
  'equipmentItems' : Array<PackageEquipmentItem>,
  'totalPrice' : bigint,
}
export interface CreateStaffRequest {
  'name' : string,
  'role' : string,
  'email' : string,
  'phone' : string,
}
export interface DashboardStats {
  'totalEquipment' : bigint,
  'pendingConfirmations' : bigint,
  'totalBookings' : bigint,
  'revenueThisMonth' : bigint,
  'equipmentUtilizationPct' : bigint,
  'activeEvents' : bigint,
}
export type DispatchStatus = { 'pending' : null } |
  { 'dispatched' : null } |
  { 'returned' : null };
export interface Equipment {
  'id' : EquipmentId,
  'status' : EquipmentStatus,
  'qrCodeData' : string,
  'availableQuantity' : bigint,
  'name' : string,
  'maintenanceNotes' : string,
  'category' : string,
  'unitPrice' : bigint,
  'totalQuantity' : bigint,
}
export type EquipmentId = string;
export type EquipmentStatus = { 'Available' : null } |
  { 'Maintenance' : null } |
  { 'Booked' : null };
export interface EventTypeCount { 'count' : bigint, 'eventType' : string }
export interface Logistics {
  'id' : LogisticsId,
  'bookingId' : BookingId,
  'dispatchStatus' : DispatchStatus,
  'createdAt' : bigint,
  'updatedAt' : bigint,
  'checklist' : Array<ChecklistItem>,
}
export type LogisticsId = string;
export interface MonthlyRevenue {
  'month' : bigint,
  'revenue' : bigint,
  'year' : bigint,
}
export interface Package {
  'id' : PackageId,
  'name' : string,
  'description' : string,
  'isActive' : boolean,
  'equipmentItems' : Array<PackageEquipmentItem>,
  'totalPrice' : bigint,
}
export interface PackageEquipmentItem {
  'quantity' : bigint,
  'equipmentId' : EquipmentId,
}
export type PackageId = string;
export interface Payment {
  'id' : PaymentId,
  'status' : PaymentStatus,
  'bookingId' : BookingId,
  'createdAt' : bigint,
  'stripePaymentIntentId' : string,
  'amount' : bigint,
}
export type PaymentId = string;
export type PaymentStatus = { 'paid' : null } |
  { 'unpaid' : null } |
  { 'partiallyPaid' : null };
export interface Quotation {
  'bookingId' : BookingId,
  'generatedAt' : bigint,
  'totalAmount' : bigint,
  'items' : Array<QuotationItem>,
}
export interface QuotationItem {
  'itemId' : string,
  'itemName' : string,
  'quantity' : bigint,
  'unitPrice' : bigint,
  'subtotal' : bigint,
}
export interface Staff {
  'id' : StaffId,
  'assignedEventIds' : Array<BookingId>,
  'name' : string,
  'role' : string,
  'email' : string,
  'phone' : string,
  'availabilityStatus' : StaffAvailability,
}
export type StaffAvailability = { 'Available' : null } |
  { 'Unavailable' : null };
export type StaffId = string;
export interface TopEquipmentItem {
  'name' : string,
  'count' : bigint,
  'equipmentId' : string,
}
export interface UpdateEquipmentRequest {
  'status' : EquipmentStatus,
  'name' : string,
  'maintenanceNotes' : string,
  'category' : string,
  'unitPrice' : bigint,
  'totalQuantity' : bigint,
}
export interface UpdatePackageRequest {
  'name' : string,
  'description' : string,
  'isActive' : boolean,
  'equipmentItems' : Array<PackageEquipmentItem>,
  'totalPrice' : bigint,
}
export interface UserProfile {
  'name' : string,
  'role' : UserRole,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'client' : null } |
  { 'admin' : null } |
  { 'staff' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addChecklistItem' : ActorMethod<[LogisticsId, string, string], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'assignStaffToEvent' : ActorMethod<[StaffId, BookingId], boolean>,
  'createBooking' : ActorMethod<[CreateBookingRequest], BookingId>,
  'createEquipment' : ActorMethod<[CreateEquipmentRequest], EquipmentId>,
  'createLogistics' : ActorMethod<[BookingId], LogisticsId>,
  'createPackage' : ActorMethod<[CreatePackageRequest], PackageId>,
  'createPayment' : ActorMethod<[BookingId, bigint, string], PaymentId>,
  'createStaff' : ActorMethod<[CreateStaffRequest], StaffId>,
  'deleteEquipment' : ActorMethod<[EquipmentId], boolean>,
  'deletePackage' : ActorMethod<[PackageId], boolean>,
  'getActivePackages' : ActorMethod<[], Array<Package>>,
  'getAllLogistics' : ActorMethod<[], Array<Logistics>>,
  'getAllPackages' : ActorMethod<[], Array<Package>>,
  'getAllPayments' : ActorMethod<[], Array<Payment>>,
  'getAllStaff' : ActorMethod<[], Array<Staff>>,
  'getAvailableEquipment' : ActorMethod<[bigint], Array<Equipment>>,
  'getBooking' : ActorMethod<[BookingId], [] | [Booking]>,
  'getBookings' : ActorMethod<[], Array<Booking>>,
  'getBookingsByEventType' : ActorMethod<[], Array<EventTypeCount>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getEquipment' : ActorMethod<[[] | [EquipmentStatus]], Array<Equipment>>,
  'getEquipmentById' : ActorMethod<[EquipmentId], [] | [Equipment]>,
  'getLogistics' : ActorMethod<[BookingId], [] | [Logistics]>,
  'getPackageById' : ActorMethod<[PackageId], [] | [Package]>,
  'getPaymentsByBooking' : ActorMethod<[BookingId], Array<Payment>>,
  'getQuotation' : ActorMethod<[BookingId], [] | [Quotation]>,
  'getRevenueByMonth' : ActorMethod<[], Array<MonthlyRevenue>>,
  'getStaffById' : ActorMethod<[StaffId], [] | [Staff]>,
  'getTopEquipment' : ActorMethod<[bigint], Array<TopEquipmentItem>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'seedEquipment' : ActorMethod<[], undefined>,
  'seedPackages' : ActorMethod<[], undefined>,
  'seedStaff' : ActorMethod<[], undefined>,
  'toggleEquipmentMaintenance' : ActorMethod<[EquipmentId, string], boolean>,
  'unassignStaffFromEvent' : ActorMethod<[StaffId, BookingId], boolean>,
  'updateBookingStatus' : ActorMethod<[BookingId, BookingStatus], boolean>,
  'updateChecklistItem' : ActorMethod<
    [LogisticsId, string, boolean, [] | [string]],
    boolean
  >,
  'updateEquipment' : ActorMethod<
    [EquipmentId, UpdateEquipmentRequest],
    boolean
  >,
  'updateLogisticsStatus' : ActorMethod<[LogisticsId, DispatchStatus], boolean>,
  'updatePackage' : ActorMethod<[PackageId, UpdatePackageRequest], boolean>,
  'updatePaymentStatus' : ActorMethod<[PaymentId, PaymentStatus], boolean>,
  'updateStaffAvailability' : ActorMethod<
    [StaffId, StaffAvailability],
    boolean
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];