/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const LogisticsId = IDL.Text;
export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const StaffId = IDL.Text;
export const BookingId = IDL.Text;
export const PackageId = IDL.Text;
export const EquipmentId = IDL.Text;
export const CreateBookingRequest = IDL.Record({
  'clientNotes' : IDL.Text,
  'location' : IDL.Text,
  'packageId' : IDL.Opt(PackageId),
  'eventDate' : IDL.Nat,
  'equipmentIds' : IDL.Vec(EquipmentId),
  'eventType' : IDL.Text,
});
export const CreateEquipmentRequest = IDL.Record({
  'name' : IDL.Text,
  'maintenanceNotes' : IDL.Text,
  'category' : IDL.Text,
  'unitPrice' : IDL.Nat,
  'totalQuantity' : IDL.Nat,
});
export const PackageEquipmentItem = IDL.Record({
  'quantity' : IDL.Nat,
  'equipmentId' : EquipmentId,
});
export const CreatePackageRequest = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'equipmentItems' : IDL.Vec(PackageEquipmentItem),
  'totalPrice' : IDL.Nat,
});
export const PaymentId = IDL.Text;
export const CreateStaffRequest = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const Package = IDL.Record({
  'id' : PackageId,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'equipmentItems' : IDL.Vec(PackageEquipmentItem),
  'totalPrice' : IDL.Nat,
});
export const DispatchStatus = IDL.Variant({
  'pending' : IDL.Null,
  'dispatched' : IDL.Null,
  'returned' : IDL.Null,
});
export const ChecklistItem = IDL.Record({
  'id' : IDL.Text,
  'item' : IDL.Text,
  'completed' : IDL.Bool,
  'assignedStaff' : IDL.Text,
});
export const Logistics = IDL.Record({
  'id' : LogisticsId,
  'bookingId' : BookingId,
  'dispatchStatus' : DispatchStatus,
  'createdAt' : IDL.Nat,
  'updatedAt' : IDL.Nat,
  'checklist' : IDL.Vec(ChecklistItem),
});
export const PaymentStatus = IDL.Variant({
  'paid' : IDL.Null,
  'unpaid' : IDL.Null,
  'partiallyPaid' : IDL.Null,
});
export const Payment = IDL.Record({
  'id' : PaymentId,
  'status' : PaymentStatus,
  'bookingId' : BookingId,
  'createdAt' : IDL.Nat,
  'stripePaymentIntentId' : IDL.Text,
  'amount' : IDL.Nat,
});
export const StaffAvailability = IDL.Variant({
  'Available' : IDL.Null,
  'Unavailable' : IDL.Null,
});
export const Staff = IDL.Record({
  'id' : StaffId,
  'assignedEventIds' : IDL.Vec(BookingId),
  'name' : IDL.Text,
  'role' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
  'availabilityStatus' : StaffAvailability,
});
export const EquipmentStatus = IDL.Variant({
  'Available' : IDL.Null,
  'Maintenance' : IDL.Null,
  'Booked' : IDL.Null,
});
export const Equipment = IDL.Record({
  'id' : EquipmentId,
  'status' : EquipmentStatus,
  'qrCodeData' : IDL.Text,
  'availableQuantity' : IDL.Nat,
  'name' : IDL.Text,
  'maintenanceNotes' : IDL.Text,
  'category' : IDL.Text,
  'unitPrice' : IDL.Nat,
  'totalQuantity' : IDL.Nat,
});
export const BookingStatus = IDL.Variant({
  'Confirmed' : IDL.Null,
  'Cancelled' : IDL.Null,
  'Completed' : IDL.Null,
  'Pending' : IDL.Null,
});
export const Booking = IDL.Record({
  'id' : BookingId,
  'status' : BookingStatus,
  'clientId' : IDL.Principal,
  'paymentStatus' : PaymentStatus,
  'createdAt' : IDL.Nat,
  'clientNotes' : IDL.Text,
  'updatedAt' : IDL.Nat,
  'totalPrice' : IDL.Nat,
  'location' : IDL.Text,
  'packageId' : IDL.Opt(PackageId),
  'eventDate' : IDL.Nat,
  'equipmentIds' : IDL.Vec(EquipmentId),
  'eventType' : IDL.Text,
});
export const EventTypeCount = IDL.Record({
  'count' : IDL.Nat,
  'eventType' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'client' : IDL.Null,
  'admin' : IDL.Null,
  'staff' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : UserRole,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const DashboardStats = IDL.Record({
  'totalEquipment' : IDL.Nat,
  'pendingConfirmations' : IDL.Nat,
  'totalBookings' : IDL.Nat,
  'revenueThisMonth' : IDL.Nat,
  'equipmentUtilizationPct' : IDL.Nat,
  'activeEvents' : IDL.Nat,
});
export const QuotationItem = IDL.Record({
  'itemId' : IDL.Text,
  'itemName' : IDL.Text,
  'quantity' : IDL.Nat,
  'unitPrice' : IDL.Nat,
  'subtotal' : IDL.Nat,
});
export const Quotation = IDL.Record({
  'bookingId' : BookingId,
  'generatedAt' : IDL.Nat,
  'totalAmount' : IDL.Nat,
  'items' : IDL.Vec(QuotationItem),
});
export const MonthlyRevenue = IDL.Record({
  'month' : IDL.Nat,
  'revenue' : IDL.Nat,
  'year' : IDL.Nat,
});
export const TopEquipmentItem = IDL.Record({
  'name' : IDL.Text,
  'count' : IDL.Nat,
  'equipmentId' : IDL.Text,
});
export const UpdateEquipmentRequest = IDL.Record({
  'status' : EquipmentStatus,
  'name' : IDL.Text,
  'maintenanceNotes' : IDL.Text,
  'category' : IDL.Text,
  'unitPrice' : IDL.Nat,
  'totalQuantity' : IDL.Nat,
});
export const UpdatePackageRequest = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'equipmentItems' : IDL.Vec(PackageEquipmentItem),
  'totalPrice' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addChecklistItem' : IDL.Func(
      [LogisticsId, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'assignStaffToEvent' : IDL.Func([StaffId, BookingId], [IDL.Bool], []),
  'createBooking' : IDL.Func([CreateBookingRequest], [BookingId], []),
  'createEquipment' : IDL.Func([CreateEquipmentRequest], [EquipmentId], []),
  'createLogistics' : IDL.Func([BookingId], [LogisticsId], []),
  'createPackage' : IDL.Func([CreatePackageRequest], [PackageId], []),
  'createPayment' : IDL.Func([BookingId, IDL.Nat, IDL.Text], [PaymentId], []),
  'createStaff' : IDL.Func([CreateStaffRequest], [StaffId], []),
  'deleteEquipment' : IDL.Func([EquipmentId], [IDL.Bool], []),
  'deletePackage' : IDL.Func([PackageId], [IDL.Bool], []),
  'getActivePackages' : IDL.Func([], [IDL.Vec(Package)], ['query']),
  'getAllLogistics' : IDL.Func([], [IDL.Vec(Logistics)], ['query']),
  'getAllPackages' : IDL.Func([], [IDL.Vec(Package)], ['query']),
  'getAllPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
  'getAllStaff' : IDL.Func([], [IDL.Vec(Staff)], ['query']),
  'getAvailableEquipment' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Equipment)],
      ['query'],
    ),
  'getBooking' : IDL.Func([BookingId], [IDL.Opt(Booking)], ['query']),
  'getBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getBookingsByEventType' : IDL.Func([], [IDL.Vec(EventTypeCount)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getEquipment' : IDL.Func(
      [IDL.Opt(EquipmentStatus)],
      [IDL.Vec(Equipment)],
      ['query'],
    ),
  'getEquipmentById' : IDL.Func([EquipmentId], [IDL.Opt(Equipment)], ['query']),
  'getLogistics' : IDL.Func([BookingId], [IDL.Opt(Logistics)], ['query']),
  'getPackageById' : IDL.Func([PackageId], [IDL.Opt(Package)], ['query']),
  'getPaymentsByBooking' : IDL.Func([BookingId], [IDL.Vec(Payment)], ['query']),
  'getQuotation' : IDL.Func([BookingId], [IDL.Opt(Quotation)], ['query']),
  'getRevenueByMonth' : IDL.Func([], [IDL.Vec(MonthlyRevenue)], ['query']),
  'getStaffById' : IDL.Func([StaffId], [IDL.Opt(Staff)], ['query']),
  'getTopEquipment' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(TopEquipmentItem)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'seedEquipment' : IDL.Func([], [], []),
  'seedPackages' : IDL.Func([], [], []),
  'seedStaff' : IDL.Func([], [], []),
  'toggleEquipmentMaintenance' : IDL.Func(
      [EquipmentId, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'unassignStaffFromEvent' : IDL.Func([StaffId, BookingId], [IDL.Bool], []),
  'updateBookingStatus' : IDL.Func([BookingId, BookingStatus], [IDL.Bool], []),
  'updateChecklistItem' : IDL.Func(
      [LogisticsId, IDL.Text, IDL.Bool, IDL.Opt(IDL.Text)],
      [IDL.Bool],
      [],
    ),
  'updateEquipment' : IDL.Func(
      [EquipmentId, UpdateEquipmentRequest],
      [IDL.Bool],
      [],
    ),
  'updateLogisticsStatus' : IDL.Func(
      [LogisticsId, DispatchStatus],
      [IDL.Bool],
      [],
    ),
  'updatePackage' : IDL.Func([PackageId, UpdatePackageRequest], [IDL.Bool], []),
  'updatePaymentStatus' : IDL.Func([PaymentId, PaymentStatus], [IDL.Bool], []),
  'updateStaffAvailability' : IDL.Func(
      [StaffId, StaffAvailability],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const LogisticsId = IDL.Text;
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const StaffId = IDL.Text;
  const BookingId = IDL.Text;
  const PackageId = IDL.Text;
  const EquipmentId = IDL.Text;
  const CreateBookingRequest = IDL.Record({
    'clientNotes' : IDL.Text,
    'location' : IDL.Text,
    'packageId' : IDL.Opt(PackageId),
    'eventDate' : IDL.Nat,
    'equipmentIds' : IDL.Vec(EquipmentId),
    'eventType' : IDL.Text,
  });
  const CreateEquipmentRequest = IDL.Record({
    'name' : IDL.Text,
    'maintenanceNotes' : IDL.Text,
    'category' : IDL.Text,
    'unitPrice' : IDL.Nat,
    'totalQuantity' : IDL.Nat,
  });
  const PackageEquipmentItem = IDL.Record({
    'quantity' : IDL.Nat,
    'equipmentId' : EquipmentId,
  });
  const CreatePackageRequest = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'equipmentItems' : IDL.Vec(PackageEquipmentItem),
    'totalPrice' : IDL.Nat,
  });
  const PaymentId = IDL.Text;
  const CreateStaffRequest = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Package = IDL.Record({
    'id' : PackageId,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'equipmentItems' : IDL.Vec(PackageEquipmentItem),
    'totalPrice' : IDL.Nat,
  });
  const DispatchStatus = IDL.Variant({
    'pending' : IDL.Null,
    'dispatched' : IDL.Null,
    'returned' : IDL.Null,
  });
  const ChecklistItem = IDL.Record({
    'id' : IDL.Text,
    'item' : IDL.Text,
    'completed' : IDL.Bool,
    'assignedStaff' : IDL.Text,
  });
  const Logistics = IDL.Record({
    'id' : LogisticsId,
    'bookingId' : BookingId,
    'dispatchStatus' : DispatchStatus,
    'createdAt' : IDL.Nat,
    'updatedAt' : IDL.Nat,
    'checklist' : IDL.Vec(ChecklistItem),
  });
  const PaymentStatus = IDL.Variant({
    'paid' : IDL.Null,
    'unpaid' : IDL.Null,
    'partiallyPaid' : IDL.Null,
  });
  const Payment = IDL.Record({
    'id' : PaymentId,
    'status' : PaymentStatus,
    'bookingId' : BookingId,
    'createdAt' : IDL.Nat,
    'stripePaymentIntentId' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const StaffAvailability = IDL.Variant({
    'Available' : IDL.Null,
    'Unavailable' : IDL.Null,
  });
  const Staff = IDL.Record({
    'id' : StaffId,
    'assignedEventIds' : IDL.Vec(BookingId),
    'name' : IDL.Text,
    'role' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
    'availabilityStatus' : StaffAvailability,
  });
  const EquipmentStatus = IDL.Variant({
    'Available' : IDL.Null,
    'Maintenance' : IDL.Null,
    'Booked' : IDL.Null,
  });
  const Equipment = IDL.Record({
    'id' : EquipmentId,
    'status' : EquipmentStatus,
    'qrCodeData' : IDL.Text,
    'availableQuantity' : IDL.Nat,
    'name' : IDL.Text,
    'maintenanceNotes' : IDL.Text,
    'category' : IDL.Text,
    'unitPrice' : IDL.Nat,
    'totalQuantity' : IDL.Nat,
  });
  const BookingStatus = IDL.Variant({
    'Confirmed' : IDL.Null,
    'Cancelled' : IDL.Null,
    'Completed' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const Booking = IDL.Record({
    'id' : BookingId,
    'status' : BookingStatus,
    'clientId' : IDL.Principal,
    'paymentStatus' : PaymentStatus,
    'createdAt' : IDL.Nat,
    'clientNotes' : IDL.Text,
    'updatedAt' : IDL.Nat,
    'totalPrice' : IDL.Nat,
    'location' : IDL.Text,
    'packageId' : IDL.Opt(PackageId),
    'eventDate' : IDL.Nat,
    'equipmentIds' : IDL.Vec(EquipmentId),
    'eventType' : IDL.Text,
  });
  const EventTypeCount = IDL.Record({
    'count' : IDL.Nat,
    'eventType' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'client' : IDL.Null,
    'admin' : IDL.Null,
    'staff' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : UserRole,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const DashboardStats = IDL.Record({
    'totalEquipment' : IDL.Nat,
    'pendingConfirmations' : IDL.Nat,
    'totalBookings' : IDL.Nat,
    'revenueThisMonth' : IDL.Nat,
    'equipmentUtilizationPct' : IDL.Nat,
    'activeEvents' : IDL.Nat,
  });
  const QuotationItem = IDL.Record({
    'itemId' : IDL.Text,
    'itemName' : IDL.Text,
    'quantity' : IDL.Nat,
    'unitPrice' : IDL.Nat,
    'subtotal' : IDL.Nat,
  });
  const Quotation = IDL.Record({
    'bookingId' : BookingId,
    'generatedAt' : IDL.Nat,
    'totalAmount' : IDL.Nat,
    'items' : IDL.Vec(QuotationItem),
  });
  const MonthlyRevenue = IDL.Record({
    'month' : IDL.Nat,
    'revenue' : IDL.Nat,
    'year' : IDL.Nat,
  });
  const TopEquipmentItem = IDL.Record({
    'name' : IDL.Text,
    'count' : IDL.Nat,
    'equipmentId' : IDL.Text,
  });
  const UpdateEquipmentRequest = IDL.Record({
    'status' : EquipmentStatus,
    'name' : IDL.Text,
    'maintenanceNotes' : IDL.Text,
    'category' : IDL.Text,
    'unitPrice' : IDL.Nat,
    'totalQuantity' : IDL.Nat,
  });
  const UpdatePackageRequest = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'equipmentItems' : IDL.Vec(PackageEquipmentItem),
    'totalPrice' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addChecklistItem' : IDL.Func(
        [LogisticsId, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'assignStaffToEvent' : IDL.Func([StaffId, BookingId], [IDL.Bool], []),
    'createBooking' : IDL.Func([CreateBookingRequest], [BookingId], []),
    'createEquipment' : IDL.Func([CreateEquipmentRequest], [EquipmentId], []),
    'createLogistics' : IDL.Func([BookingId], [LogisticsId], []),
    'createPackage' : IDL.Func([CreatePackageRequest], [PackageId], []),
    'createPayment' : IDL.Func([BookingId, IDL.Nat, IDL.Text], [PaymentId], []),
    'createStaff' : IDL.Func([CreateStaffRequest], [StaffId], []),
    'deleteEquipment' : IDL.Func([EquipmentId], [IDL.Bool], []),
    'deletePackage' : IDL.Func([PackageId], [IDL.Bool], []),
    'getActivePackages' : IDL.Func([], [IDL.Vec(Package)], ['query']),
    'getAllLogistics' : IDL.Func([], [IDL.Vec(Logistics)], ['query']),
    'getAllPackages' : IDL.Func([], [IDL.Vec(Package)], ['query']),
    'getAllPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
    'getAllStaff' : IDL.Func([], [IDL.Vec(Staff)], ['query']),
    'getAvailableEquipment' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Equipment)],
        ['query'],
      ),
    'getBooking' : IDL.Func([BookingId], [IDL.Opt(Booking)], ['query']),
    'getBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getBookingsByEventType' : IDL.Func(
        [],
        [IDL.Vec(EventTypeCount)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getEquipment' : IDL.Func(
        [IDL.Opt(EquipmentStatus)],
        [IDL.Vec(Equipment)],
        ['query'],
      ),
    'getEquipmentById' : IDL.Func(
        [EquipmentId],
        [IDL.Opt(Equipment)],
        ['query'],
      ),
    'getLogistics' : IDL.Func([BookingId], [IDL.Opt(Logistics)], ['query']),
    'getPackageById' : IDL.Func([PackageId], [IDL.Opt(Package)], ['query']),
    'getPaymentsByBooking' : IDL.Func(
        [BookingId],
        [IDL.Vec(Payment)],
        ['query'],
      ),
    'getQuotation' : IDL.Func([BookingId], [IDL.Opt(Quotation)], ['query']),
    'getRevenueByMonth' : IDL.Func([], [IDL.Vec(MonthlyRevenue)], ['query']),
    'getStaffById' : IDL.Func([StaffId], [IDL.Opt(Staff)], ['query']),
    'getTopEquipment' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(TopEquipmentItem)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'seedEquipment' : IDL.Func([], [], []),
    'seedPackages' : IDL.Func([], [], []),
    'seedStaff' : IDL.Func([], [], []),
    'toggleEquipmentMaintenance' : IDL.Func(
        [EquipmentId, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'unassignStaffFromEvent' : IDL.Func([StaffId, BookingId], [IDL.Bool], []),
    'updateBookingStatus' : IDL.Func(
        [BookingId, BookingStatus],
        [IDL.Bool],
        [],
      ),
    'updateChecklistItem' : IDL.Func(
        [LogisticsId, IDL.Text, IDL.Bool, IDL.Opt(IDL.Text)],
        [IDL.Bool],
        [],
      ),
    'updateEquipment' : IDL.Func(
        [EquipmentId, UpdateEquipmentRequest],
        [IDL.Bool],
        [],
      ),
    'updateLogisticsStatus' : IDL.Func(
        [LogisticsId, DispatchStatus],
        [IDL.Bool],
        [],
      ),
    'updatePackage' : IDL.Func(
        [PackageId, UpdatePackageRequest],
        [IDL.Bool],
        [],
      ),
    'updatePaymentStatus' : IDL.Func(
        [PaymentId, PaymentStatus],
        [IDL.Bool],
        [],
      ),
    'updateStaffAvailability' : IDL.Func(
        [StaffId, StaffAvailability],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };