/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type EquipmentId = string;
export interface MonthlyRevenue {
    month: bigint;
    revenue: bigint;
    year: bigint;
}
export interface Equipment {
    id: EquipmentId;
    status: EquipmentStatus;
    qrCodeData: string;
    availableQuantity: bigint;
    name: string;
    maintenanceNotes: string;
    category: string;
    unitPrice: bigint;
    totalQuantity: bigint;
}
export interface CreatePackageRequest {
    name: string;
    description: string;
    equipmentItems: Array<PackageEquipmentItem>;
    totalPrice: bigint;
}
export interface TopEquipmentItem {
    name: string;
    count: bigint;
    equipmentId: string;
}
export type LogisticsId = string;
export interface Quotation {
    bookingId: BookingId;
    generatedAt: bigint;
    totalAmount: bigint;
    items: Array<QuotationItem>;
}
export interface Staff {
    id: StaffId;
    assignedEventIds: Array<BookingId>;
    name: string;
    role: string;
    email: string;
    phone: string;
    availabilityStatus: StaffAvailability;
}
export type PackageId = string;
export interface UpdatePackageRequest {
    name: string;
    description: string;
    isActive: boolean;
    equipmentItems: Array<PackageEquipmentItem>;
    totalPrice: bigint;
}
export interface Booking {
    id: BookingId;
    status: BookingStatus;
    clientId: Principal;
    paymentStatus: PaymentStatus;
    createdAt: bigint;
    clientNotes: string;
    updatedAt: bigint;
    totalPrice: bigint;
    location: string;
    packageId?: PackageId;
    eventDate: bigint;
    equipmentIds: Array<EquipmentId>;
    eventType: string;
}
export type BookingId = string;
export type StaffId = string;
export interface CreateBookingRequest {
    clientNotes: string;
    location: string;
    packageId?: PackageId;
    eventDate: bigint;
    equipmentIds: Array<EquipmentId>;
    eventType: string;
}
export interface Logistics {
    id: LogisticsId;
    bookingId: BookingId;
    dispatchStatus: DispatchStatus;
    createdAt: bigint;
    updatedAt: bigint;
    checklist: Array<ChecklistItem>;
}
export interface UpdateEquipmentRequest {
    status: EquipmentStatus;
    name: string;
    maintenanceNotes: string;
    category: string;
    unitPrice: bigint;
    totalQuantity: bigint;
}
export interface Payment {
    id: PaymentId;
    status: PaymentStatus;
    bookingId: BookingId;
    createdAt: bigint;
    stripePaymentIntentId: string;
    amount: bigint;
}
export interface Package {
    id: PackageId;
    name: string;
    description: string;
    isActive: boolean;
    equipmentItems: Array<PackageEquipmentItem>;
    totalPrice: bigint;
}
export interface EventTypeCount {
    count: bigint;
    eventType: string;
}
export interface PackageEquipmentItem {
    quantity: bigint;
    equipmentId: EquipmentId;
}
export interface DashboardStats {
    totalEquipment: bigint;
    pendingConfirmations: bigint;
    totalBookings: bigint;
    revenueThisMonth: bigint;
    equipmentUtilizationPct: bigint;
    activeEvents: bigint;
}
export interface CreateStaffRequest {
    name: string;
    role: string;
    email: string;
    phone: string;
}
export interface QuotationItem {
    itemId: string;
    itemName: string;
    quantity: bigint;
    unitPrice: bigint;
    subtotal: bigint;
}
export interface CreateEquipmentRequest {
    name: string;
    maintenanceNotes: string;
    category: string;
    unitPrice: bigint;
    totalQuantity: bigint;
}
export type PaymentId = string;
export interface ChecklistItem {
    id: string;
    item: string;
    completed: boolean;
    assignedStaff: string;
}
export interface UserProfile {
    name: string;
    role: UserRole;
    email: string;
    phone: string;
}
export enum BookingStatus {
    Confirmed = "Confirmed",
    Cancelled = "Cancelled",
    Completed = "Completed",
    Pending = "Pending"
}
export enum DispatchStatus {
    pending = "pending",
    dispatched = "dispatched",
    returned = "returned"
}
export enum EquipmentStatus {
    Available = "Available",
    Maintenance = "Maintenance",
    Booked = "Booked"
}
export enum PaymentStatus {
    paid = "paid",
    unpaid = "unpaid",
    partiallyPaid = "partiallyPaid"
}
export enum StaffAvailability {
    Available = "Available",
    Unavailable = "Unavailable"
}
export enum UserRole {
    client = "client",
    admin = "admin",
    staff = "staff"
}
export enum UserRole__1 {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    addChecklistItem(id: LogisticsId, item: string, assignedStaff: string): Promise<boolean>;
    assignCallerUserRole(user: Principal, role: UserRole__1): Promise<void>;
    assignStaffToEvent(staffId: StaffId, eventId: BookingId): Promise<boolean>;
    createBooking(req: CreateBookingRequest): Promise<BookingId>;
    createEquipment(req: CreateEquipmentRequest): Promise<EquipmentId>;
    createLogistics(bookingId: BookingId): Promise<LogisticsId>;
    createPackage(req: CreatePackageRequest): Promise<PackageId>;
    createPayment(bookingId: BookingId, amount: bigint, stripePaymentIntentId: string): Promise<PaymentId>;
    createStaff(req: CreateStaffRequest): Promise<StaffId>;
    deleteEquipment(id: EquipmentId): Promise<boolean>;
    deletePackage(id: PackageId): Promise<boolean>;
    getActivePackages(): Promise<Array<Package>>;
    getAllLogistics(): Promise<Array<Logistics>>;
    getAllPackages(): Promise<Array<Package>>;
    getAllPayments(): Promise<Array<Payment>>;
    getAllStaff(): Promise<Array<Staff>>;
    getAvailableEquipment(eventDate: bigint): Promise<Array<Equipment>>;
    getBooking(id: BookingId): Promise<Booking | null>;
    getBookings(): Promise<Array<Booking>>;
    getBookingsByEventType(): Promise<Array<EventTypeCount>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole__1>;
    getDashboardStats(): Promise<DashboardStats>;
    getEquipment(statusFilter: EquipmentStatus | null): Promise<Array<Equipment>>;
    getEquipmentById(id: EquipmentId): Promise<Equipment | null>;
    getLogistics(bookingId: BookingId): Promise<Logistics | null>;
    getPackageById(id: PackageId): Promise<Package | null>;
    getPaymentsByBooking(bookingId: BookingId): Promise<Array<Payment>>;
    getQuotation(bookingId: BookingId): Promise<Quotation | null>;
    getRevenueByMonth(): Promise<Array<MonthlyRevenue>>;
    getStaffById(id: StaffId): Promise<Staff | null>;
    getTopEquipment(limit: bigint): Promise<Array<TopEquipmentItem>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    seedEquipment(): Promise<void>;
    seedPackages(): Promise<void>;
    seedStaff(): Promise<void>;
    toggleEquipmentMaintenance(id: EquipmentId, notes: string): Promise<boolean>;
    unassignStaffFromEvent(staffId: StaffId, eventId: BookingId): Promise<boolean>;
    updateBookingStatus(id: BookingId, newStatus: BookingStatus): Promise<boolean>;
    updateChecklistItem(id: LogisticsId, checklistItemId: string, completed: boolean, newItemText: string | null): Promise<boolean>;
    updateEquipment(id: EquipmentId, req: UpdateEquipmentRequest): Promise<boolean>;
    updateLogisticsStatus(id: LogisticsId, newStatus: DispatchStatus): Promise<boolean>;
    updatePackage(id: PackageId, req: UpdatePackageRequest): Promise<boolean>;
    updatePaymentStatus(id: PaymentId, newStatus: PaymentStatus): Promise<boolean>;
    updateStaffAvailability(staffId: StaffId, status: StaffAvailability): Promise<boolean>;
}
import type { Booking as _Booking, BookingId as _BookingId, BookingStatus as _BookingStatus, ChecklistItem as _ChecklistItem, CreateBookingRequest as _CreateBookingRequest, DispatchStatus as _DispatchStatus, Equipment as _Equipment, EquipmentId as _EquipmentId, EquipmentStatus as _EquipmentStatus, Logistics as _Logistics, LogisticsId as _LogisticsId, Package as _Package, PackageId as _PackageId, Payment as _Payment, PaymentId as _PaymentId, PaymentStatus as _PaymentStatus, Quotation as _Quotation, Staff as _Staff, StaffAvailability as _StaffAvailability, StaffId as _StaffId, UpdateEquipmentRequest as _UpdateEquipmentRequest, UserProfile as _UserProfile, UserRole as _UserRole, UserRole__1 as _UserRole__1 } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async addChecklistItem(arg0: LogisticsId, arg1: string, arg2: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.addChecklistItem(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addChecklistItem(arg0, arg1, arg2);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole__1): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignStaffToEvent(arg0: StaffId, arg1: BookingId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.assignStaffToEvent(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignStaffToEvent(arg0, arg1);
            return result;
        }
    }
    async createBooking(arg0: CreateBookingRequest): Promise<BookingId> {
        if (this.processError) {
            try {
                const result = await this.actor.createBooking(to_candid_CreateBookingRequest_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBooking(to_candid_CreateBookingRequest_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createEquipment(arg0: CreateEquipmentRequest): Promise<EquipmentId> {
        if (this.processError) {
            try {
                const result = await this.actor.createEquipment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createEquipment(arg0);
            return result;
        }
    }
    async createLogistics(arg0: BookingId): Promise<LogisticsId> {
        if (this.processError) {
            try {
                const result = await this.actor.createLogistics(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createLogistics(arg0);
            return result;
        }
    }
    async createPackage(arg0: CreatePackageRequest): Promise<PackageId> {
        if (this.processError) {
            try {
                const result = await this.actor.createPackage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPackage(arg0);
            return result;
        }
    }
    async createPayment(arg0: BookingId, arg1: bigint, arg2: string): Promise<PaymentId> {
        if (this.processError) {
            try {
                const result = await this.actor.createPayment(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPayment(arg0, arg1, arg2);
            return result;
        }
    }
    async createStaff(arg0: CreateStaffRequest): Promise<StaffId> {
        if (this.processError) {
            try {
                const result = await this.actor.createStaff(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createStaff(arg0);
            return result;
        }
    }
    async deleteEquipment(arg0: EquipmentId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEquipment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEquipment(arg0);
            return result;
        }
    }
    async deletePackage(arg0: PackageId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePackage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePackage(arg0);
            return result;
        }
    }
    async getActivePackages(): Promise<Array<Package>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActivePackages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActivePackages();
            return result;
        }
    }
    async getAllLogistics(): Promise<Array<Logistics>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLogistics();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLogistics();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPackages(): Promise<Array<Package>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPackages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPackages();
            return result;
        }
    }
    async getAllPayments(): Promise<Array<Payment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPayments();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPayments();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllStaff(): Promise<Array<Staff>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStaff();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStaff();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAvailableEquipment(arg0: bigint): Promise<Array<Equipment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableEquipment(arg0);
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableEquipment(arg0);
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBooking(arg0: BookingId): Promise<Booking | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBooking(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBooking(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookings();
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookings();
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookingsByEventType(): Promise<Array<EventTypeCount>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingsByEventType();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingsByEventType();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole__1> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole__1_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole__1_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getEquipment(arg0: EquipmentStatus | null): Promise<Array<Equipment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEquipment(to_candid_opt_n39(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEquipment(to_candid_opt_n39(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEquipmentById(arg0: EquipmentId): Promise<Equipment | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getEquipmentById(arg0);
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEquipmentById(arg0);
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLogistics(arg0: BookingId): Promise<Logistics | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLogistics(arg0);
                return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLogistics(arg0);
            return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPackageById(arg0: PackageId): Promise<Package | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPackageById(arg0);
                return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPackageById(arg0);
            return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPaymentsByBooking(arg0: BookingId): Promise<Array<Payment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaymentsByBooking(arg0);
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaymentsByBooking(arg0);
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQuotation(arg0: BookingId): Promise<Quotation | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuotation(arg0);
                return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuotation(arg0);
            return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRevenueByMonth(): Promise<Array<MonthlyRevenue>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRevenueByMonth();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRevenueByMonth();
            return result;
        }
    }
    async getStaffById(arg0: StaffId): Promise<Staff | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStaffById(arg0);
                return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStaffById(arg0);
            return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTopEquipment(arg0: bigint): Promise<Array<TopEquipmentItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTopEquipment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTopEquipment(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n47(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n47(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async seedEquipment(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedEquipment();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedEquipment();
            return result;
        }
    }
    async seedPackages(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedPackages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedPackages();
            return result;
        }
    }
    async seedStaff(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedStaff();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedStaff();
            return result;
        }
    }
    async toggleEquipmentMaintenance(arg0: EquipmentId, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleEquipmentMaintenance(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleEquipmentMaintenance(arg0, arg1);
            return result;
        }
    }
    async unassignStaffFromEvent(arg0: StaffId, arg1: BookingId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.unassignStaffFromEvent(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unassignStaffFromEvent(arg0, arg1);
            return result;
        }
    }
    async updateBookingStatus(arg0: BookingId, arg1: BookingStatus): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBookingStatus(arg0, to_candid_BookingStatus_n51(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBookingStatus(arg0, to_candid_BookingStatus_n51(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateChecklistItem(arg0: LogisticsId, arg1: string, arg2: boolean, arg3: string | null): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateChecklistItem(arg0, arg1, arg2, to_candid_opt_n53(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateChecklistItem(arg0, arg1, arg2, to_candid_opt_n53(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async updateEquipment(arg0: EquipmentId, arg1: UpdateEquipmentRequest): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEquipment(arg0, to_candid_UpdateEquipmentRequest_n54(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEquipment(arg0, to_candid_UpdateEquipmentRequest_n54(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateLogisticsStatus(arg0: LogisticsId, arg1: DispatchStatus): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLogisticsStatus(arg0, to_candid_DispatchStatus_n56(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLogisticsStatus(arg0, to_candid_DispatchStatus_n56(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updatePackage(arg0: PackageId, arg1: UpdatePackageRequest): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePackage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePackage(arg0, arg1);
            return result;
        }
    }
    async updatePaymentStatus(arg0: PaymentId, arg1: PaymentStatus): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePaymentStatus(arg0, to_candid_PaymentStatus_n58(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePaymentStatus(arg0, to_candid_PaymentStatus_n58(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateStaffAvailability(arg0: StaffId, arg1: StaffAvailability): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStaffAvailability(arg0, to_candid_StaffAvailability_n60(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStaffAvailability(arg0, to_candid_StaffAvailability_n60(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_BookingStatus_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingStatus): BookingStatus {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_Booking_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Booking): Booking {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_DispatchStatus_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DispatchStatus): DispatchStatus {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_EquipmentStatus_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EquipmentStatus): EquipmentStatus {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_Equipment_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Equipment): Equipment {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_Logistics_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Logistics): Logistics {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentStatus_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentStatus): PaymentStatus {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Payment_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Payment): Payment {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_StaffAvailability_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StaffAvailability): StaffAvailability {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_Staff_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Staff): Staff {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole__1_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole__1): UserRole__1 {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Booking]): Booking | null {
    return value.length === 0 ? null : from_candid_Booking_n26(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PackageId]): PackageId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n33(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Equipment]): Equipment | null {
    return value.length === 0 ? null : from_candid_Equipment_n21(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Logistics]): Logistics | null {
    return value.length === 0 ? null : from_candid_Logistics_n6(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Package]): Package | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Quotation]): Quotation | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Staff]): Staff | null {
    return value.length === 0 ? null : from_candid_Staff_n16(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _PaymentId;
    status: _PaymentStatus;
    bookingId: _BookingId;
    createdAt: bigint;
    stripePaymentIntentId: string;
    amount: bigint;
}): {
    id: PaymentId;
    status: PaymentStatus;
    bookingId: BookingId;
    createdAt: bigint;
    stripePaymentIntentId: string;
    amount: bigint;
} {
    return {
        id: value.id,
        status: from_candid_PaymentStatus_n13(_uploadFile, _downloadFile, value.status),
        bookingId: value.bookingId,
        createdAt: value.createdAt,
        stripePaymentIntentId: value.stripePaymentIntentId,
        amount: value.amount
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _StaffId;
    assignedEventIds: Array<_BookingId>;
    name: string;
    role: string;
    email: string;
    phone: string;
    availabilityStatus: _StaffAvailability;
}): {
    id: StaffId;
    assignedEventIds: Array<BookingId>;
    name: string;
    role: string;
    email: string;
    phone: string;
    availabilityStatus: StaffAvailability;
} {
    return {
        id: value.id,
        assignedEventIds: value.assignedEventIds,
        name: value.name,
        role: value.role,
        email: value.email,
        phone: value.phone,
        availabilityStatus: from_candid_StaffAvailability_n18(_uploadFile, _downloadFile, value.availabilityStatus)
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _EquipmentId;
    status: _EquipmentStatus;
    qrCodeData: string;
    availableQuantity: bigint;
    name: string;
    maintenanceNotes: string;
    category: string;
    unitPrice: bigint;
    totalQuantity: bigint;
}): {
    id: EquipmentId;
    status: EquipmentStatus;
    qrCodeData: string;
    availableQuantity: bigint;
    name: string;
    maintenanceNotes: string;
    category: string;
    unitPrice: bigint;
    totalQuantity: bigint;
} {
    return {
        id: value.id,
        status: from_candid_EquipmentStatus_n23(_uploadFile, _downloadFile, value.status),
        qrCodeData: value.qrCodeData,
        availableQuantity: value.availableQuantity,
        name: value.name,
        maintenanceNotes: value.maintenanceNotes,
        category: value.category,
        unitPrice: value.unitPrice,
        totalQuantity: value.totalQuantity
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _BookingId;
    status: _BookingStatus;
    clientId: Principal;
    paymentStatus: _PaymentStatus;
    createdAt: bigint;
    clientNotes: string;
    updatedAt: bigint;
    totalPrice: bigint;
    location: string;
    packageId: [] | [_PackageId];
    eventDate: bigint;
    equipmentIds: Array<_EquipmentId>;
    eventType: string;
}): {
    id: BookingId;
    status: BookingStatus;
    clientId: Principal;
    paymentStatus: PaymentStatus;
    createdAt: bigint;
    clientNotes: string;
    updatedAt: bigint;
    totalPrice: bigint;
    location: string;
    packageId?: PackageId;
    eventDate: bigint;
    equipmentIds: Array<EquipmentId>;
    eventType: string;
} {
    return {
        id: value.id,
        status: from_candid_BookingStatus_n28(_uploadFile, _downloadFile, value.status),
        clientId: value.clientId,
        paymentStatus: from_candid_PaymentStatus_n13(_uploadFile, _downloadFile, value.paymentStatus),
        createdAt: value.createdAt,
        clientNotes: value.clientNotes,
        updatedAt: value.updatedAt,
        totalPrice: value.totalPrice,
        location: value.location,
        packageId: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.packageId)),
        eventDate: value.eventDate,
        equipmentIds: value.equipmentIds,
        eventType: value.eventType
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: _UserRole;
    email: string;
    phone: string;
}): {
    name: string;
    role: UserRole;
    email: string;
    phone: string;
} {
    return {
        name: value.name,
        role: from_candid_UserRole_n35(_uploadFile, _downloadFile, value.role),
        email: value.email,
        phone: value.phone
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _LogisticsId;
    bookingId: _BookingId;
    dispatchStatus: _DispatchStatus;
    createdAt: bigint;
    updatedAt: bigint;
    checklist: Array<_ChecklistItem>;
}): {
    id: LogisticsId;
    bookingId: BookingId;
    dispatchStatus: DispatchStatus;
    createdAt: bigint;
    updatedAt: bigint;
    checklist: Array<ChecklistItem>;
} {
    return {
        id: value.id,
        bookingId: value.bookingId,
        dispatchStatus: from_candid_DispatchStatus_n8(_uploadFile, _downloadFile, value.dispatchStatus),
        createdAt: value.createdAt,
        updatedAt: value.updatedAt,
        checklist: value.checklist
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    paid: null;
} | {
    unpaid: null;
} | {
    partiallyPaid: null;
}): PaymentStatus {
    return "paid" in value ? PaymentStatus.paid : "unpaid" in value ? PaymentStatus.unpaid : "partiallyPaid" in value ? PaymentStatus.partiallyPaid : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Available: null;
} | {
    Unavailable: null;
}): StaffAvailability {
    return "Available" in value ? StaffAvailability.Available : "Unavailable" in value ? StaffAvailability.Unavailable : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Available: null;
} | {
    Maintenance: null;
} | {
    Booked: null;
}): EquipmentStatus {
    return "Available" in value ? EquipmentStatus.Available : "Maintenance" in value ? EquipmentStatus.Maintenance : "Booked" in value ? EquipmentStatus.Booked : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Confirmed: null;
} | {
    Cancelled: null;
} | {
    Completed: null;
} | {
    Pending: null;
}): BookingStatus {
    return "Confirmed" in value ? BookingStatus.Confirmed : "Cancelled" in value ? BookingStatus.Cancelled : "Completed" in value ? BookingStatus.Completed : "Pending" in value ? BookingStatus.Pending : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    client: null;
} | {
    admin: null;
} | {
    staff: null;
}): UserRole {
    return "client" in value ? UserRole.client : "admin" in value ? UserRole.admin : "staff" in value ? UserRole.staff : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole__1 {
    return "admin" in value ? UserRole__1.admin : "user" in value ? UserRole__1.user : "guest" in value ? UserRole__1.guest : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    dispatched: null;
} | {
    returned: null;
}): DispatchStatus {
    return "pending" in value ? DispatchStatus.pending : "dispatched" in value ? DispatchStatus.dispatched : "returned" in value ? DispatchStatus.returned : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Payment>): Array<Payment> {
    return value.map((x)=>from_candid_Payment_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Staff>): Array<Staff> {
    return value.map((x)=>from_candid_Staff_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Equipment>): Array<Equipment> {
    return value.map((x)=>from_candid_Equipment_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Booking>): Array<Booking> {
    return value.map((x)=>from_candid_Booking_n26(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Logistics>): Array<Logistics> {
    return value.map((x)=>from_candid_Logistics_n6(_uploadFile, _downloadFile, x));
}
function to_candid_BookingStatus_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): _BookingStatus {
    return to_candid_variant_n52(_uploadFile, _downloadFile, value);
}
function to_candid_CreateBookingRequest_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateBookingRequest): _CreateBookingRequest {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_DispatchStatus_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DispatchStatus): _DispatchStatus {
    return to_candid_variant_n57(_uploadFile, _downloadFile, value);
}
function to_candid_EquipmentStatus_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EquipmentStatus): _EquipmentStatus {
    return to_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentStatus_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentStatus): _PaymentStatus {
    return to_candid_variant_n59(_uploadFile, _downloadFile, value);
}
function to_candid_StaffAvailability_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StaffAvailability): _StaffAvailability {
    return to_candid_variant_n61(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateEquipmentRequest_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateEquipmentRequest): _UpdateEquipmentRequest {
    return to_candid_record_n55(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n48(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole__1_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): _UserRole__1 {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n50(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EquipmentStatus | null): [] | [_EquipmentStatus] {
    return value === null ? candid_none() : candid_some(to_candid_EquipmentStatus_n40(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    clientNotes: string;
    location: string;
    packageId?: PackageId;
    eventDate: bigint;
    equipmentIds: Array<EquipmentId>;
    eventType: string;
}): {
    clientNotes: string;
    location: string;
    packageId: [] | [_PackageId];
    eventDate: bigint;
    equipmentIds: Array<_EquipmentId>;
    eventType: string;
} {
    return {
        clientNotes: value.clientNotes,
        location: value.location,
        packageId: value.packageId ? candid_some(value.packageId) : candid_none(),
        eventDate: value.eventDate,
        equipmentIds: value.equipmentIds,
        eventType: value.eventType
    };
}
function to_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: UserRole;
    email: string;
    phone: string;
}): {
    name: string;
    role: _UserRole;
    email: string;
    phone: string;
} {
    return {
        name: value.name,
        role: to_candid_UserRole_n49(_uploadFile, _downloadFile, value.role),
        email: value.email,
        phone: value.phone
    };
}
function to_candid_record_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: EquipmentStatus;
    name: string;
    maintenanceNotes: string;
    category: string;
    unitPrice: bigint;
    totalQuantity: bigint;
}): {
    status: _EquipmentStatus;
    name: string;
    maintenanceNotes: string;
    category: string;
    unitPrice: bigint;
    totalQuantity: bigint;
} {
    return {
        status: to_candid_EquipmentStatus_n40(_uploadFile, _downloadFile, value.status),
        name: value.name,
        maintenanceNotes: value.maintenanceNotes,
        category: value.category,
        unitPrice: value.unitPrice,
        totalQuantity: value.totalQuantity
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole__1.admin ? {
        admin: null
    } : value == UserRole__1.user ? {
        user: null
    } : value == UserRole__1.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EquipmentStatus): {
    Available: null;
} | {
    Maintenance: null;
} | {
    Booked: null;
} {
    return value == EquipmentStatus.Available ? {
        Available: null
    } : value == EquipmentStatus.Maintenance ? {
        Maintenance: null
    } : value == EquipmentStatus.Booked ? {
        Booked: null
    } : value;
}
function to_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    client: null;
} | {
    admin: null;
} | {
    staff: null;
} {
    return value == UserRole.client ? {
        client: null
    } : value == UserRole.admin ? {
        admin: null
    } : value == UserRole.staff ? {
        staff: null
    } : value;
}
function to_candid_variant_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): {
    Confirmed: null;
} | {
    Cancelled: null;
} | {
    Completed: null;
} | {
    Pending: null;
} {
    return value == BookingStatus.Confirmed ? {
        Confirmed: null
    } : value == BookingStatus.Cancelled ? {
        Cancelled: null
    } : value == BookingStatus.Completed ? {
        Completed: null
    } : value == BookingStatus.Pending ? {
        Pending: null
    } : value;
}
function to_candid_variant_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DispatchStatus): {
    pending: null;
} | {
    dispatched: null;
} | {
    returned: null;
} {
    return value == DispatchStatus.pending ? {
        pending: null
    } : value == DispatchStatus.dispatched ? {
        dispatched: null
    } : value == DispatchStatus.returned ? {
        returned: null
    } : value;
}
function to_candid_variant_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentStatus): {
    paid: null;
} | {
    unpaid: null;
} | {
    partiallyPaid: null;
} {
    return value == PaymentStatus.paid ? {
        paid: null
    } : value == PaymentStatus.unpaid ? {
        unpaid: null
    } : value == PaymentStatus.partiallyPaid ? {
        partiallyPaid: null
    } : value;
}
function to_candid_variant_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StaffAvailability): {
    Available: null;
} | {
    Unavailable: null;
} {
    return value == StaffAvailability.Available ? {
        Available: null
    } : value == StaffAvailability.Unavailable ? {
        Unavailable: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
